name: Mastonaut

options:
  deploymentTarget:
    macOS: "12.0"

configs:
  Debug: debug
  Mock: mock
  Release: release
  Release HSE: release-hse

fileGroups:
  - userspecific.xcconfig

packages:
  LoggingOSLog:
    url: https://github.com/chrisaljoudi/swift-log-oslog.git
    branch: master
  FontPicker:
    url: https://github.com/chucker/FontPicker.git
    branch: main
  Sdifft:
    url: https://github.com/wzxhahaha/Sdifft
    majorVersion: 2.0.0
  Starscream:
    url: https://github.com/daltoniam/Starscream.git
    majorVersion: 3.1.0
  SVGKit:
    url: https://github.com/SVGKit/SVGKit
    majorVersion: 3.0.0
  DSFSparkline:
    url: https://github.com/dagronf/DSFSparkline
    majorVersion: 4.0.0

targets:
  Mastonaut:
    type: application
    platform: macOS
    settings:
      base:
        INFOPLIST_FILE: "Mastonaut/Supporting Files/Info.plist"
        SWIFT_OBJC_BRIDGING_HEADER: "Mastonaut/Supporting Files/Mastonaut-Bridging-Header.h"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.social-networking"
        MARKETING_VERSION: "1.3.9"
        CURRENT_PROJECT_VERSION: "135"
        PRODUCT_BUNDLE_IDENTIFIER: "$(MASTONAUT_BUNDLE_ID_BASE).mac"
        OTHER_LDFLAGS: ""
    preBuildScripts:
      - script: |
                BUNDLE_VERSION=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' $SRCROOT/Mastonaut/Supporting\ Files/Info.plist)
                echo "#define BUNDLE_VERSION \"$MARKETING_VERSION\"" > $DERIVED_FILE_DIR/BundleVersions.h
        inputFiles:
          - "$(SRCROOT)/Mastonaut/Supporting Files/Info.plist"
        outputFiles:
          - "$(DERIVED_FILE_DIR)/BundleVersions.h"
    # configFiles:
    #   # don't add these globally; it breaks linking
    #   Debug: userspecific.xcconfig
    #   Mock: userspecific.xcconfig
    #   Release: userspecific.xcconfig
    #   Release HSE: userspecific.xcconfig
    sources:
      - path: Mastonaut
      - path: "CoreTootin/Supporting Files/BuildConfig.generated.swift"
      - path: "CoreTootin/Extensions/Logger+CurrentType.swift"
    dependencies:
      # - package: CocoaLumberjack
      - package: FontPicker
      - package: LoggingOSLog
      - package: Sdifft
      - package: Starscream
      - package: SVGKit
      - target: CoreTootin
      - target: MastodonKit
      - target: PullRefreshableScrollView
  Mastonaut (Mock):
    type: application
    platform: macOS
    sources:
      - path: Mastonaut
  QuickToot:
    type: app-extension
    platform: macOS
    sources:
      - path: QuickToot
  MastonautTests:
    type: bundle.unit-test
    platform: macOS
  CoreTootin:
    type: framework
    platform: macOS
    preBuildScripts:
      - script: |
                "$PROJECT_DIR/Mastonaut/Supporting Files/BuildConfig.sh" \
                > "${PROJECT_DIR}/CoreTootin/Supporting Files/BuildConfig.generated.swift"
        outputFiles:
          - "${PROJECT_DIR}/CoreTootin/Supporting Files/BuildConfig.generated.swift"
    settings:
      base:
        OTHER_LDFLAGS: ""
    configFiles:
      # don't add these globally; it breaks linking
      Debug: userspecific.xcconfig
      Mock: userspecific.xcconfig
      Release: userspecific.xcconfig
      Release HSE: userspecific.xcconfig
    sources:
      - path: CoreTootin
        excludes:
          - "CoreTootin/Extensions/Logger+CurrentType.swift"
    dependencies:
      - package: DSFSparkline
  MastodonKit:
    type: framework
    platform: macOS
    sources:
      - path: Dependencies/MastodonKit/Sources/MastodonKit
        name: MastodonKit
  MastonautHelp:
    type: bundle
    platform: macOS
    sources:
      - path: MastonautHelp
  PullRefreshableScrollView:
    type: framework
    platform: macOS
    sources:
    - path: Dependencies/PullRefreshableScrollView/PullRefreshableScrollView
      group: Dependencies
